/* eslint-disable no-unused-vars */
const QueryKeys = {
	GET_VERIFIED_EMAILS: "GET_VERIFIED_EMAILS",
	GET_SKILLS: "GET_SKILLS",
	GET_ROLES: "GET_ROLES",
	GET_PROFILE: "GET_PROFILE",
	GET_PROJECTS: "GET_PROJECTS",
	GET_UNREAD_NOTIFICATION: "GET_UNREAD_NOTIFICATION",
	GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
} as const;

export default QueryKeys;
